name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  BuildSystemApplication:
    runs-on: windows-2019
    env:
      BC_CONTAINER_USERNAME: admin
      BC_CONTAINER_PASSWORD: P@ssword1
    steps:
      - uses: actions/checkout@v1    
      - name: Install BcContainerHelper
        shell: powershell
        run: Install-Module BcContainerHelper -Force

      - name: Set up Business Central container
        shell: powershell
        run: >
          New-BCContainer 
          -accept_eula 
          -containerName bcdev 
          -artifactUrl (Get-BcArtifactUrl -type sandbox -country us -select latest)
          -alwaysPull 
          -auth NavUserPassword 
          -credential ([PSCredential]::new($Env:BC_CONTAINER_USERNAME, (ConvertTo-SecureString -String $Env:BC_CONTAINER_PASSWORD -AsPlainText -Force))) 
          -updateHosts
          -additionalParameters @("--volume $Env:GITHUB_WORKSPACE\Modules\System`:c:\project")
          -includeAL

      - name: Compile System Application  
        shell: powershell
        run: >
          $pathToJson = $Env:GITHUB_WORKSPACE\Modules\System\app.json;
          $AppJsonFile = Get-Content $pathToJson | ConvertFrom-Json;
          $AppJsonFile.version = [string]([int]($AppJsonFile.version.substring(0, 2)) + 1) + $AppJsonFile.version.substring(2);
          $AppJsonFile | ConvertTo-Json | Set-Content $pathToJson;

          Compile-AppInBCContainer 
          -containerName bcdev 
          -credential ([PSCredential]::new($Env:BC_CONTAINER_USERNAME, (ConvertTo-SecureString -String $Env:BC_CONTAINER_PASSWORD -AsPlainText -Force))) 
          -appProjectFolder $Env:GITHUB_WORKSPACE\Modules\System
          -appOutputFolder $Env:GITHUB_WORKSPACE\Modules\System
          -EnableCodeCop
          -EnableUICop

      - name: Publish System Application  
        shell: powershell
        run: >
          Publish-BcContainerApp  
          -containerName bcdev 
          -credential ([PSCredential]::new($Env:BC_CONTAINER_USERNAME, (ConvertTo-SecureString -String $Env:BC_CONTAINER_PASSWORD -AsPlainText -Force))) 
          -appFile (gci $Env:GITHUB_WORKSPACE\Modules\System -Filter "*.app").FullName
          -skipVerification
          -install
          -sync

