name: CI

on:
  pull_request:
    branches: [ master ]

jobs:  
  run:
    name: Verify changeset
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: docker://mcr.microsoft.com/businesscentral:10.0.19042.685
    - name: Build and run
      shell: powershell
      env:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
      run: |
        Write-Host "Installing BcContainerHelper..."
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module BcContainerHelper -force
        
        Write-Host "Importing BcContainerHelper..."
        Import-Module BcContainerHelper -DisableNameChecking
        
        Write-Host "Getting BC artifacts..."
        $artifactUrl = Get-BcArtifactUrl -type sandbox -country us -select latest
        
        Write-Host "Creating a new container..."
        $passwordSecureString = ConvertTo-SecureString -String "$env:password" -AsPlainText -Force
        $credential = New-Object pscredential "$env:username", $passwordSecureString
        New-BCContainer -accept_eula -containerName test -artifactUrl $artifactUrl -auth AAD -authenticationEMail "$env:username"
