name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1    
      - name: Install BcContainerHelper
        shell: powershell
        run: Install-Module BcContainerHelper -Force

      - name: Set environment variables
        shell: powershell
        run: |
          $password = New-Guid
          echo "USERNAME=admin" >> $GITHUB_ENV
          echo "PASSWORD=$password" >> $GITHUB_ENV

      - name: Set up Business Central container
        env:
          USERNAME: ${{ env.USERNAME }}
          PASSWORD: ${{ env.PASSWORD }}
        shell: powershell
        run: >
          New-BCContainer 
          -accept_eula 
          -containerName bcdev 
          -artifactUrl (Get-BcArtifactUrl -type sandbox -country us -select latest)
          -useBestContainerOS 
          -alwaysPull 
          -auth NavUserPassword 
          -credential ([PSCredential]::new($Env:USERNAME, (ConvertTo-SecureString -String $Env:PASSWORD -AsPlainText -Force))) 
          -updateHosts
          -additionalParameters @("--volume $Env:GITHUB_WORKSPACE\Modules\System`:c:\project")
          -includeAL

      - name: Compile System Application
        env:
          USERNAME: ${{ env.USERNAME }}
          PASSWORD: ${{ env.PASSWORD }}    
        shell: powershell
        run: >
          Compile-AppInBCContainer 
          -containerName bcdev 
          -credential ([PSCredential]::new($Env:USERNAME, (ConvertTo-SecureString -String $Env:PASSWORD -AsPlainText -Force))) 
          -appProjectFolder $Env:GITHUB_WORKSPACE\Modules\System
          -appOutputFolder $Env:GITHUB_WORKSPACE\Modules\System
          -EnableCodeCop
          -EnableUICop
