name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1    
      - name: Install NavContainerHelper
        run: Install-Module NavContainerHelper -Force
        shell: powershell
      - name: Set up Business Central container
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: >
          New-NavContainer 
          -accept_eula 
          -containerName bcdev 
          -imageName mcr.microsoft.com/businesscentral/onprem:latest 
          -useBestContainerOS 
          -alwaysPull 
          -auth NavUserPassword 
          -credential ([PSCredential]::new($Env:USERNAME, (ConvertTo-SecureString -String $Env:PASSWORD -AsPlainText -Force))) 
          -updateHosts 
          -doNotExportObjectsToText 
          -enableSymbolLoading
          -additionalParameters @("--volume $Env:GITHUB_WORKSPACE\ALAppExtensions\Modules\System`:c:\project")
        shell: powershell
      - name: Compile extension
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}    
        run: >
          Compile-AppInBCContainer 
          -containerName bcdev 
          -credential ([PSCredential]::new($Env:USERNAME, (ConvertTo-SecureString -String $Env:PASSWORD -AsPlainText -Force))) 
          -appProjectFolder $Env:GITHUB_WORKSPACE\ALAppExtensions\Modules\System
          -appOutputFolder $Env:GITHUB_WORKSPACE\ALAppExtensions\Modules\System
          -updateSymbols
        shell: powershell
      - name: Publish extension
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: >
          Publish-NavContainerApp 
          -containerName bcdev 
          -credential ([PSCredential]::new($Env:USERNAME, (ConvertTo-SecureString -String $Env:PASSWORD -AsPlainText -Force))) 
          -appFile ((Get-ChildItem -Path $Env:GITHUB_WORKSPACE\ALAppExtensions\Modules\System -File *.app).FullName)
          -skipVerification
          -sync 
          -install
        shell: powershell
