name: CI

on:
  pull_request:
    branches: [ master ]

jobs:  
  run:
    name: Verify changeset
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build and run
      shell: powershell
      env:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module BcContainerHelper -force
        Import-Module BcContainerHelper -DisableNameChecking
        $artifactUrl = Get-BcArtifactUrl -type sandbox -country us -select latest
        $credential = New-Object pscredential "$username", (ConvertTo-SecureString -String "$password" -AsPlainText -Force)
        New-BCContainer -accept_eula -containerName test -artifactUrl $artifactUrl -auth AAD -authenticationEMail "$username"
